export const size100 = 'var(--font-size-100)'
export const size200 = 'var(--font-size-200)'
export const size300 = 'var(--font-size-300)'
export const size400 = 'var(--font-size-400)'
export const size500 = 'var(--font-size-500)'
export const size600 = 'var(--font-size-600)'
export const size700 = 'var(--font-size-700)'
export const size800 = 'var(--font-size-800)'
export const size900 = 'var(--font-size-900)'

export const regular = 'var(--font-weight-regular)'
export const medium = 'var(--font-weight-medium)'
export const bold = 'var(--font-weight-extra-bold)'
export const black = 'var(--font-weight-black)'
